-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.bills (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  bill_number character varying NOT NULL UNIQUE,
  bill_type character varying NOT NULL CHECK (bill_type::text = ANY (ARRAY['tax_invoice'::character varying, 'receipt'::character varying]::text[])),
  booking_id uuid NOT NULL,
  customer_name character varying NOT NULL,
  customer_email character varying,
  customer_phone character varying,
  subtotal numeric NOT NULL DEFAULT 0,
  tax_amount numeric NOT NULL DEFAULT 0,
  total_amount numeric NOT NULL DEFAULT 0,
  tax_rate numeric DEFAULT 0.00,
  status character varying DEFAULT 'draft'::character varying CHECK (status::text = ANY (ARRAY['draft'::character varying, 'issued'::character varying, 'paid'::character varying, 'cancelled'::character varying, 'complete'::character varying, 'incomplete'::character varying]::text[])),
  issue_date date DEFAULT CURRENT_DATE,
  due_date date,
  paid_date date,
  description text,
  notes text,
  payment_method character varying,
  auto_generated boolean DEFAULT false,
  parent_bill_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT bills_pkey PRIMARY KEY (id),
  CONSTRAINT bills_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id),
  CONSTRAINT bills_parent_bill_id_fkey FOREIGN KEY (parent_bill_id) REFERENCES public.bills(id)
);
CREATE TABLE public.booking_services (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_id uuid NOT NULL,
  service_type character varying NOT NULL CHECK (service_type::text = ANY (ARRAY['guides'::character varying::text, 'paramedics'::character varying::text, 'security_companies'::character varying::text, 'external_entertainment_companies'::character varying::text, 'travel_companies'::character varying::text, 'education_programs'::character varying::text])),
  service_id uuid NOT NULL,
  quantity integer NOT NULL DEFAULT 1 CHECK (quantity > 0),
  days integer NOT NULL DEFAULT 1 CHECK (days > 0),
  booked_price numeric NOT NULL DEFAULT 0,
  rate_type character varying DEFAULT 'fixed'::character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  acceptance_status character varying DEFAULT 'pending'::character varying CHECK (acceptance_status::text = ANY (ARRAY['pending'::character varying::text, 'accepted'::character varying::text, 'rejected'::character varying::text])),
  accepted_at timestamp with time zone,
  rejected_at timestamp with time zone,
  rejection_reason text,
  responded_by uuid,
  CONSTRAINT booking_services_pkey PRIMARY KEY (id),
  CONSTRAINT booking_services_booking_id_fkey FOREIGN KEY (booking_id) REFERENCES public.bookings(id),
  CONSTRAINT booking_services_responded_by_fkey FOREIGN KEY (responded_by) REFERENCES public.users(id)
);
CREATE TABLE public.bookings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  booking_reference character varying NOT NULL UNIQUE,
  destination_id uuid,
  trip_date date NOT NULL,
  total_amount numeric NOT NULL DEFAULT 0,
  payment_status character varying DEFAULT 'pending'::character varying CHECK (payment_status::text = ANY (ARRAY['pending'::character varying, 'deposit_paid'::character varying, 'fully_paid'::character varying, 'cancelled'::character varying, 'paid'::character varying]::text[])),
  payment_method character varying DEFAULT 'bank_transfer'::character varying,
  status character varying DEFAULT 'confirmed'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying, 'confirmed'::character varying, 'completed'::character varying, 'cancelled'::character varying, 'active'::character varying, 'inactive'::character varying]::text[])),
  notes text,
  special_requests text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  customer_id uuid NOT NULL,
  booking_type character varying NOT NULL DEFAULT 'full_trip'::character varying CHECK (booking_type::text = ANY (ARRAY['full_trip'::character varying, 'guides_only'::character varying, 'paramedics_only'::character varying, 'security_only'::character varying, 'entertainment_only'::character varying, 'transportation_only'::character varying, 'education_only'::character varying]::text[])),
  number_of_students integer,
  number_of_crew integer,
  number_of_buses integer,
  school_id uuid,
  CONSTRAINT bookings_pkey PRIMARY KEY (id),
  CONSTRAINT bookings_destination_id_fkey FOREIGN KEY (destination_id) REFERENCES public.destinations(id),
  CONSTRAINT bookings_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES public.users(id),
  CONSTRAINT bookings_school_id_fkey FOREIGN KEY (school_id) REFERENCES public.schools(id)
);
CREATE TABLE public.company_settings (
  name character varying NOT NULL,
  logo_url text,
  address text,
  phone character varying,
  tax_number character varying,
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  email text,
  CONSTRAINT company_settings_pkey PRIMARY KEY (id)
);
CREATE TABLE public.destination_properties (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  value text NOT NULL UNIQUE,
  icon text,
  is_active boolean NOT NULL DEFAULT true,
  display_order integer DEFAULT 0,
  CONSTRAINT destination_properties_pkey PRIMARY KEY (id)
);
CREATE TABLE public.destination_properties_link (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  destination_id uuid NOT NULL,
  property_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT destination_properties_link_pkey PRIMARY KEY (id),
  CONSTRAINT destination_properties_link_destination_fkey FOREIGN KEY (destination_id) REFERENCES public.destinations(id),
  CONSTRAINT destination_properties_link_property_fkey FOREIGN KEY (property_id) REFERENCES public.destination_properties(id)
);
CREATE TABLE public.destination_suitable_for_link (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  destination_id uuid NOT NULL,
  suitable_for_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT destination_suitable_for_link_pkey PRIMARY KEY (id),
  CONSTRAINT destination_suitable_for_link_destination_fkey FOREIGN KEY (destination_id) REFERENCES public.destinations(id),
  CONSTRAINT destination_suitable_for_link_suitable_for_fkey FOREIGN KEY (suitable_for_id) REFERENCES public.suitable_for_options(id)
);
CREATE TABLE public.destinations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  name text NOT NULL,
  address text,
  phone text,
  zone_id uuid,
  description text,
  thumbnail_path text,
  gallery_paths ARRAY DEFAULT '{}'::text[],
  properties jsonb DEFAULT '[]'::jsonb,
  requirements jsonb DEFAULT '[]'::jsonb,
  suitable_for ARRAY DEFAULT '{}'::text[],
  pricing jsonb DEFAULT '{}'::jsonb,
  is_active boolean NOT NULL DEFAULT true,
  CONSTRAINT destinations_pkey PRIMARY KEY (id),
  CONSTRAINT destinations_zone_id_fkey FOREIGN KEY (zone_id) REFERENCES public.zones(id)
);
CREATE TABLE public.destinations_pricing_backup (
  id uuid,
  name text,
  pricing jsonb,
  created_at timestamp with time zone
);
CREATE TABLE public.education_program_services (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  education_program_id uuid NOT NULL,
  service_label character varying NOT NULL,
  service_price numeric NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT education_program_services_pkey PRIMARY KEY (id),
  CONSTRAINT education_program_services_education_program_id_fkey FOREIGN KEY (education_program_id) REFERENCES public.education_programs(id)
);
CREATE TABLE public.education_programs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  name character varying NOT NULL,
  profile_picture_path text,
  description text,
  price numeric,
  status character varying DEFAULT 'active'::character varying CHECK (status::text = ANY (ARRAY['active'::character varying::text, 'inactive'::character varying::text])),
  user_id uuid,
  CONSTRAINT education_programs_pkey PRIMARY KEY (id),
  CONSTRAINT education_programs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.entertainment_company_services (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  entertainment_company_id uuid NOT NULL,
  service_label character varying NOT NULL,
  service_price numeric NOT NULL DEFAULT 0 CHECK (service_price >= 0::numeric),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT entertainment_company_services_pkey PRIMARY KEY (id),
  CONSTRAINT entertainment_company_services_entertainment_company_id_fkey FOREIGN KEY (entertainment_company_id) REFERENCES public.external_entertainment_companies(id)
);
CREATE TABLE public.external_entertainment_companies (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  name character varying NOT NULL,
  profile_picture_path text,
  description text,
  price numeric,
  status character varying DEFAULT 'active'::character varying CHECK (status::text = ANY (ARRAY['active'::character varying, 'inactive'::character varying]::text[])),
  user_id uuid,
  CONSTRAINT external_entertainment_companies_pkey PRIMARY KEY (id),
  CONSTRAINT external_entertainment_companies_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.guides (
  name character varying NOT NULL,
  identity_number character varying NOT NULL UNIQUE,
  phone character varying,
  email character varying,
  hourly_rate numeric,
  daily_rate numeric,
  regional_rate numeric,
  overnight_rate numeric,
  status character varying DEFAULT 'active'::character varying CHECK (status::text = ANY (ARRAY['active'::character varying, 'inactive'::character varying]::text[])),
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  profile_picture_path text,
  CONSTRAINT guides_pkey PRIMARY KEY (id),
  CONSTRAINT guides_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.paramedics (
  name character varying NOT NULL,
  identity_number character varying NOT NULL UNIQUE,
  phone character varying,
  email character varying,
  hourly_rate numeric,
  daily_rate numeric,
  regional_rate numeric,
  overnight_rate numeric,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  notes text,
  status text CHECK (status = ANY (ARRAY['active'::text, 'inactive'::text])),
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  profile_picture_path text,
  CONSTRAINT paramedics_pkey PRIMARY KEY (id),
  CONSTRAINT paramedics_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.payments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  bill_id uuid NOT NULL,
  amount numeric NOT NULL,
  payment_type character varying NOT NULL CHECK (payment_type::text = ANY (ARRAY['cash'::character varying, 'bank_transfer'::character varying, 'credit_card'::character varying, 'check'::character varying]::text[])),
  account_number character varying,
  account_holder_name character varying,
  bank_name character varying,
  transaction_number character varying,
  card_number character varying,
  card_holder_name character varying,
  check_number character varying,
  check_bank_name character varying,
  payer_name character varying,
  payment_date date DEFAULT CURRENT_DATE,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT payments_pkey PRIMARY KEY (id),
  CONSTRAINT payments_bill_id_fkey FOREIGN KEY (bill_id) REFERENCES public.bills(id)
);
CREATE TABLE public.payouts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  type character varying NOT NULL DEFAULT 'payment'::character varying CHECK (type::text = ANY (ARRAY['booking'::character varying::text, 'payment'::character varying::text])),
  service_type character varying NOT NULL CHECK (service_type::text = ANY (ARRAY['guides'::character varying::text, 'paramedics'::character varying::text, 'security_companies'::character varying::text, 'external_entertainment_companies'::character varying::text, 'travel_companies'::character varying::text, 'education_programs'::character varying::text])),
  service_id uuid NOT NULL,
  user_id uuid NOT NULL,
  service_provider_name character varying NOT NULL,
  amount numeric NOT NULL CHECK (amount > 0::numeric),
  payment_method character varying NOT NULL CHECK (payment_method::text = ANY (ARRAY['cash'::character varying::text, 'bank_transfer'::character varying::text, 'credit_card'::character varying::text, 'check'::character varying::text])),
  payment_date date NOT NULL DEFAULT CURRENT_DATE,
  account_number character varying,
  account_holder_name character varying,
  bank_name character varying,
  transaction_number character varying,
  reference_number character varying,
  check_number character varying,
  check_bank_name character varying,
  description text,
  notes text,
  booking_service_id uuid,
  booking_record_id uuid,
  status character varying DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying::text, 'paid'::character varying::text, 'cancelled'::character varying::text])),
  created_by uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT payouts_pkey PRIMARY KEY (id),
  CONSTRAINT payouts_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT payouts_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT payouts_booking_service_id_fkey FOREIGN KEY (booking_service_id) REFERENCES public.booking_services(id),
  CONSTRAINT payouts_booking_record_id_fkey FOREIGN KEY (booking_record_id) REFERENCES public.payouts(id)
);
CREATE TABLE public.schools (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  name character varying NOT NULL,
  code character varying UNIQUE,
  type character varying NOT NULL,
  director_name character varying,
  address text,
  email character varying,
  phone character varying,
  staff_count integer DEFAULT 0,
  student_count integer DEFAULT 0,
  class_count integer DEFAULT 0,
  status character varying DEFAULT 'active'::character varying,
  notes text,
  CONSTRAINT schools_pkey PRIMARY KEY (id)
);
CREATE TABLE public.security_companies (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  name character varying NOT NULL,
  tax_number character varying,
  phone character varying,
  email character varying,
  address text,
  license_types text,
  weapon_types text,
  status character varying DEFAULT 'active'::character varying CHECK (status::text = ANY (ARRAY['active'::character varying, 'inactive'::character varying]::text[])),
  notes text,
  hourly_rate numeric DEFAULT 50.00,
  daily_rate numeric DEFAULT 400.00,
  regional_rate numeric DEFAULT 600.00,
  overnight_rate numeric DEFAULT 500.00,
  user_id uuid,
  profile_picture_path text,
  CONSTRAINT security_companies_pkey PRIMARY KEY (id),
  CONSTRAINT security_companies_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.students (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  student_id character varying NOT NULL UNIQUE,
  first_name character varying NOT NULL,
  last_name character varying NOT NULL,
  email character varying,
  phone character varying,
  date_of_birth date,
  grade_level character varying,
  class_section character varying,
  parent_guardian_name character varying,
  parent_guardian_phone character varying,
  parent_guardian_email character varying,
  emergency_contact_name character varying,
  emergency_contact_phone character varying,
  medical_conditions text,
  allergies text,
  address text,
  status character varying DEFAULT 'active'::character varying,
  avatar_url text,
  notes text,
  CONSTRAINT students_pkey PRIMARY KEY (id)
);
CREATE TABLE public.suitable_for_options (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  value text NOT NULL UNIQUE,
  is_active boolean NOT NULL DEFAULT true,
  display_order integer DEFAULT 0,
  CONSTRAINT suitable_for_options_pkey PRIMARY KEY (id)
);
CREATE TABLE public.travel_companies (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL,
  code character varying NOT NULL UNIQUE,
  services_offered text,
  vehicle_count integer DEFAULT 0,
  vehicle_availability character varying DEFAULT 'available'::character varying CHECK (vehicle_availability::text = ANY (ARRAY['available'::character varying, 'busy'::character varying, 'maintenance'::character varying]::text[])),
  accounting_methods text,
  address text NOT NULL,
  email character varying NOT NULL,
  phone character varying NOT NULL,
  status character varying DEFAULT 'active'::character varying CHECK (status::text = ANY (ARRAY['active'::character varying, 'inactive'::character varying]::text[])),
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  pricing_data jsonb,
  user_id uuid,
  profile_picture_path text,
  CONSTRAINT travel_companies_pkey PRIMARY KEY (id),
  CONSTRAINT travel_companies_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.trip_buses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  trip_id uuid,
  bus_id uuid,
  driver_id uuid,
  departure_time time without time zone,
  return_time time without time zone,
  route_details text,
  CONSTRAINT trip_buses_pkey PRIMARY KEY (id),
  CONSTRAINT trip_buses_trip_id_fkey FOREIGN KEY (trip_id) REFERENCES public.trips(id),
  CONSTRAINT trip_buses_driver_id_fkey FOREIGN KEY (driver_id) REFERENCES public.users(id)
);
CREATE TABLE public.trip_plans (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  school_id text NOT NULL,
  school_name text NOT NULL,
  trip_date date,
  destination_name text,
  destination_address text,
  destination_lat double precision,
  destination_lng double precision,
  travel_company_id text,
  travel_company_name text,
  travel_vehicle_type text,
  travel_area text,
  travel_price numeric DEFAULT 0,
  paramedic_ids ARRAY,
  paramedics_selection jsonb DEFAULT '[]'::jsonb,
  paramedics_total numeric DEFAULT 0,
  guide_ids ARRAY,
  guides_selection jsonb DEFAULT '[]'::jsonb,
  guides_total numeric DEFAULT 0,
  security_company_id text,
  security_company_name text,
  security_price numeric DEFAULT 0,
  entertainment_ids ARRAY,
  entertainment_selection jsonb DEFAULT '[]'::jsonb,
  entertainment_total numeric DEFAULT 0,
  total_price numeric NOT NULL DEFAULT 0,
  pricing_breakdown jsonb DEFAULT '{}'::jsonb,
  notes text,
  destination_id uuid,
  CONSTRAINT trip_plans_pkey PRIMARY KEY (id),
  CONSTRAINT trip_plans_destination_id_fkey FOREIGN KEY (destination_id) REFERENCES public.destinations(id)
);
CREATE TABLE public.trip_registrations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  trip_id uuid,
  student_id uuid,
  registration_date timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  status character varying DEFAULT 'pending'::character varying,
  payment_status character varying DEFAULT 'unpaid'::character varying,
  amount_paid numeric DEFAULT 0,
  payment_method character varying,
  special_requirements text,
  parent_consent boolean DEFAULT false,
  medical_form_submitted boolean DEFAULT false,
  emergency_contact_confirmed boolean DEFAULT false,
  registered_by uuid,
  approved_by uuid,
  CONSTRAINT trip_registrations_pkey PRIMARY KEY (id),
  CONSTRAINT trip_registrations_trip_id_fkey FOREIGN KEY (trip_id) REFERENCES public.trips(id),
  CONSTRAINT trip_registrations_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.students(id),
  CONSTRAINT trip_registrations_registered_by_fkey FOREIGN KEY (registered_by) REFERENCES public.users(id),
  CONSTRAINT trip_registrations_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.users(id)
);
CREATE TABLE public.trips (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  trip_name character varying NOT NULL,
  description text,
  destination character varying NOT NULL,
  departure_date date NOT NULL,
  return_date date NOT NULL,
  departure_time time without time zone,
  return_time time without time zone,
  max_students integer DEFAULT 30,
  cost_per_student numeric DEFAULT 0,
  grade_levels character varying,
  trip_type character varying DEFAULT 'educational'::character varying,
  status character varying DEFAULT 'planning'::character varying,
  meeting_point character varying,
  emergency_contact character varying,
  special_requirements text,
  created_by uuid,
  updated_by uuid,
  CONSTRAINT trips_pkey PRIMARY KEY (id),
  CONSTRAINT trips_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id),
  CONSTRAINT trips_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.users(id)
);
CREATE TABLE public.user_roles (
  id integer NOT NULL DEFAULT nextval('user_roles_id_seq'::regclass),
  name character varying NOT NULL UNIQUE,
  description text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_roles_pkey PRIMARY KEY (id)
);
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  email character varying NOT NULL UNIQUE,
  phone character varying,
  status character varying DEFAULT 'active'::character varying,
  avatar_url text,
  last_login_at timestamp with time zone,
  auth_user_id uuid,
  full_name character varying,
  birth_date date,
  address text,
  role_id integer,
  school_id uuid,
  is_active boolean DEFAULT true,
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.user_roles(id),
  CONSTRAINT users_school_id_fkey FOREIGN KEY (school_id) REFERENCES public.schools(id)
);
CREATE TABLE public.zones (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  name text NOT NULL,
  description text,
  address text,
  is_active boolean NOT NULL DEFAULT true,
  CONSTRAINT zones_pkey PRIMARY KEY (id)
);